DROP TABLE ACTORES_PELIS;
DROP TABLE PELICULAS;
DROP TABLE ACTORES;
DROP TABLE DIRECTORES;
DROP TABLE TEMAS;

--Creamos una tabla con los actores
CREATE TABLE ACTORES(
    COD_ACTOR NUMBER(5) PRIMARY KEY,
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDO VARCHAR2(20),
    NACIONALIDAD VARCHAR2(20),
    FECHA_NAC DATE
);
--Creamos una tabla con las tem�ticas de las pelis
CREATE TABLE TEMAS(
    COD_TEMA VARCHAR2(8) PRIMARY KEY,
    TEMA VARCHAR2(20) NOT NULL,
    DESCRIP VARCHAR2(1000)
);

--Creamos una tabla con el director de la pel�cula
CREATE TABLE DIRECTORES(
    COD_DIRECTOR NUMBER(5) PRIMARY KEY,
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDO VARCHAR2(20),
    NACIONALIDAD VARCHAR2(20),
    FECHA_NAC DATE
);

--Creamos una tabla con las pel�culas
CREATE TABLE PELICULAS(
    COD_PELICULA NUMBER(5) PRIMARY KEY,
    TITULO VARCHAR2(100) NOT NULL,
    RESUMEN VARCHAR2(1000),
    COD_DIRECTOR NUMBER(5),
    COD_TEMA VARCHAR2(8),
    FECHA DATE,
    FOREIGN KEY (COD_DIRECTOR) REFERENCES DIRECTORES(COD_DIRECTOR),
    FOREIGN KEY (COD_TEMA) REFERENCES TEMAS(COD_TEMA)
);

--Creamos una tabla con los actores relacionados con sus pel�culas
CREATE TABLE ACTORES_PELIS(
    COD_ACTOR NUMBER(5),
    COD_PELICULA NUMBER(5),
    PRIMARY KEY (COD_ACTOR, COD_PELICULA),
    FOREIGN KEY (COD_ACTOR) REFERENCES ACTORES(COD_ACTOR),
    FOREIGN KEY (COD_PELICULA) REFERENCES PELICULAS(COD_PELICULA)
);

--Insertamos directores de cine
INSERT INTO DIRECTORES VALUES(1, 'PEDRO', 'ALMODOVAR', 'ESPA�OLA', '25/02/1949');
INSERT INTO DIRECTORES VALUES(2, 'STEVEN', 'SPIELBERG', 'ESTADOUNIDENSE', '18/12/1946');
INSERT INTO DIRECTORES VALUES(3, 'QUENTIN', 'TARANTINO', 'ESTADOUNIDENSE', '27/03/1963');
INSERT INTO DIRECTORES VALUES(4, 'MARTIN', 'SCORSESE', 'ESTADOUNIDENSE', '17/11/1942');
INSERT INTO DIRECTORES VALUES(5, 'WOODY', 'ALLEN', 'ESTADOUNIDENSE', '01/12/1935');
INSERT INTO DIRECTORES VALUES(6, 'GUILLERMO', 'DEL TORO', 'ESPA�OLA', '09/10/1964');
INSERT INTO DIRECTORES VALUES(7, 'TIM', 'BURTON', 'ESTADOUNIDENSE', '25/08/1958');
INSERT INTO DIRECTORES VALUES(8, 'ALEJANDRO', 'AMENABAR', 'ESPA�OLA', '31/03/1972');
INSERT INTO DIRECTORES VALUES(9, 'FEDERICO', 'FELLINI', 'ITALIANA', '20/01/1920');

--Insertamos tem�ticas de pel�culas
INSERT INTO TEMAS VALUES('ACC', 'ACCI�N', 'G�NERO CINEMATOGR�FICO DONDE PRIMA LA ESPECTACULARIDAD DE LAS IM�GENES POR MEDIO DE EFECTOS ESPECIALES');
INSERT INTO TEMAS VALUES('ROM', 'ROM�NTICA', 'G�NERO CINEMATOGR�FICO QUE RELATA UNA HISTORIA DE AMAR DONDE LA RELACI�N ENTRE PERSONAS ES EL CENTRO DEL ARGUMENTO');
INSERT INTO TEMAS VALUES('TER', 'TERROR', 'G�NERO CINEMATOGR�FICO QUE SE CARACTERIZA POR SU VOLUNTAD DE PROVOCAR EN EL ESPECTADOR SENSACIONES DE PAVOR, TERROR Y MIEDO');
INSERT INTO TEMAS VALUES('FIC', 'CIENCIA FICCI�N', 'G�NERO CINEMATOGR�FICO QUE VERSA SOBRE EL IMPACTO QUE PRODUCEN LOS AVANCES CIENT�FICOS, TECNOL�GICOS, SOCIALES');
INSERT INTO TEMAS VALUES('DRA', 'DRAMA', 'G�NERO CINEMATOGR�FICO QUE TRATA SITUACIONES NO �PICAS EN UN ENTORNO SERIO');

--Insertamos las pelis
INSERT INTO PELICULAS VALUES(1, 'LA LEY DEL DESEO', 'AMOR FRATERNO, DE CALENTURA Y PERDICI�N EN MADRID VERANIEGO', 1, 'ROM', '07/02/1987');
INSERT INTO PELICULAS VALUES(2, 'DOS EXTRA�OS AMANTES', 'COMEDIA ROM�NTICA', 5, 'ROM', '22/02/1978');
INSERT INTO PELICULAS VALUES(3, 'EL AVIADOR', 'A�OS DORADOS DEL MULTIMILLONARIO, MAGNATE, AVIADOR Y DIRECTOR HOWARD HUGHES', 4, 'ACC', '14(01/2005');
INSERT INTO PELICULAS VALUES(4, 'MANHATTAN', 'VIDA HORRIBLE DE UN NEOYORQUINO', 5, 'ROM', '10/09/1979');
INSERT INTO PELICULAS VALUES(5, 'DEATH PROOF', 'DOS GRUPOS DE VOLUPTUOSAS MUJERES SON ACECHADAS POR UN MISTERIOSO ESPECIALISTA DE ESCENAS DE ACCI�N', 3,'ACC', '31/08/2007');
INSERT INTO PELICULAS VALUES(6, 'LA ROSA P�RPURA DE EL CAIRO', 'MIENTRAS CECILIA TRABAJA COMO CAMARERA SU MARIDO FANTASEA CON LUJOS Y FIESTAS', 5, 'ROM', '26/01/1985');
INSERT INTO PELICULAS VALUES(7, 'JO, QU� NOCHE', 'DESEPERACI�N QUE UN PROTAGONISTA QUE DESCUBRE QUE AL CAER EL SOL, LAS CALLES DE NUEVA YORK COBRAN VIDA PROPIA', 4, 'ACC','11/10/1985');
INSERT INTO PELICULAS VALUES(8, 'LOVE AND DEATH', 'BORIS EST� ENAMORADO DE SU PRIMA SONIA MIENTRAS ESTALLA LA GUERRA', 5, 'ROM', '01/10/1984');
INSERT INTO PELICULAS VALUES(9, 'ET, EL EXTRATERRESTE', 'HISTORIA DE UN EXTRATERRESTRE PERDIDO EN LA TIERRA QUE ENCUENTRA LA AMISTAD', 2, 'FIC', '06/12/1982');
INSERT INTO PELICULAS VALUES(10, 'DESMONTANDO A HARRY', 'HARRY BLOCK ESCRIBE UNA NOVELA AUTOBIOGR�FICA DANDO GRAN CANTIDAD DE DETALLES DE SU VIDA', 5, 'ROM', '27/08/1997');
INSERT INTO PELICULAS VALUES(11, 'EL REY DE LA COMEDIA', 'FALSA COMEDIA SOBRE LA FAMA, LA ADMIRACI�N Y LA NEGACI�N AL FRACASO', 4, 'DRA', '20/05/1983');
INSERT INTO PELICULAS VALUES(12, 'JACKIE BROWN', 'UNA AZAFATA INCREMENTA SU SUELDO MENSUAL TRANSPORTANDO DIVISAS', 3, 'ACC', '23/02/1998');
INSERT INTO PELICULAS VALUES(13, 'LA PIEL QUE HABITO', 'DESCRIPCI�N DE UN MISTERIO EXISTENCIAL', 1, 'TER', '02/09/2011');
INSERT INTO PELICULAS VALUES(14, 'EL IRLAND�S', 'CINE MAFIOSO ENTRE DOS AMIGOS', 4, 'ACC', '27/09/2019');
INSERT INTO PELICULAS VALUES(15, '�RASE UNA VEZ HOLLIWOOD', 'PANORAMA CAMBIANTE DE HOLLYWOOD A FINALES DE LOS A�OS 60', 3, 'ACC', '26/07/2019');
INSERT INTO PELICULAS VALUES(16, 'TAXI DRIVER', 'EXMARINE CON INSOMNIO QUE TRABAJA COMO TAXISTA Y QUE HA ENCONTRADO LA FORMA DE EMPEORAR SU SITUACI�N MENTAL', 4, 'ACC', '10/03/1977');
INSERT INTO PELICULAS VALUES(17, 'TIBUR�N', 'EN LA COSTA DE UN PEQUE�O PUEBLO UN ENORME TIBUR�N ATACA A LAS PERSONAS', 2, 'FIC', '19/12/1975');
INSERT INTO PELICULAS VALUES(18, 'LOS ODIOSOS OCHO', 'DAISY DOMERGUE UNA FUGITIVA A LA QUE LLEVAN PARA QUE AHORQUEN, ENCUENTRA REFUGIO', 3, 'ACC', '15/01/2016');
INSERT INTO PELICULAS VALUES(19, 'INFILTRADOS', 'MAFIAS Y CRIMER ORGANIZADO', 4, 'ACC', '06/10/2006');
INSERT INTO PELICULAS VALUES(20, 'MUJERES AL BORDE DE UN ATAQUE DE NERVIOS', 'ESPA�A COMPETENTE, ELEGANTE, AMABLE, LUMINOSA, POSTMODERNAS', 1, 'ACC', '25/03/1988');
INSERT INTO PELICULAS VALUES(21, 'MALDITOS BASTARDOS', 'LOS NAZIS HAN MATADO A LA FAMILIA DE UNA GRANJERA FRANCESA QUE BUSCAR� VENGANZA', 3, 'ACC', '28/07/2009');
INSERT INTO PELICULAS VALUES(22, 'UNO DE LOS NUESTROS', 'MAGN�FICO CUENTO DE MAFIOSOS', 4, 'ACC', '19/10/1990');
INSERT INTO PELICULAS VALUES(23, 'ATR�PAME SI PUEDES', 'UN JOVEN SE HACE PASAR POR PILOTO Y EMPRENDE UNA CARRERA DE ESTAFAS', 2, 'ACC', '24/01/2003');
INSERT INTO PELICULAS VALUES(24, 'DJANGO DESENCADENADO', 'UN ESCLAVO LIBERADO ES ENTRENADO POR UN CAZARRECOMPENSAS ALEM�S', 3, 'ACC', '18/01/2013');
INSERT INTO PELICULAS VALUES(25, 'KIKA', 'COMEDIA AGRESIVA QUE DETIENE EL TIEMPO EN EL VESTUARIO', 1, 'ACC', '29/10/1993');
INSERT INTO PELICULAS VALUES(26, 'JURASSIC PARK', 'ESPECIALISTA EN INGENIER�A GEN�TICA REVIVE ALGUNOS EJEMPLARES DE DINOSAURIOS', 2, 'FIC', '30/09/1993');
INSERT INTO PELICULAS VALUES(27, 'PULP FICTION', 'DOS ASESINOS A SUELDO QUE TRABAJAN PARA MARSELLUS', 3, 'ACC', '13/01/1995');
INSERT INTO PELICULAS VALUES(28, '�TAME', 'EL IDILIO DEJABA PASO LAS RA�CES Y A LA ALIANZA FEMENINA COMO N�CLEO INDESTRUCTIBLE DE LA FAMILIA', 1, 'ROM', '12/12/1989');
INSERT INTO PELICULAS VALUES(29, 'EN BUSCA DEL ARCA PERDIDA', 'LOCALIZACI�N Y RECUPERACI�N DEL ARCA DE LA ALIANZA', 2, 'ACC', '05/10/1981');
INSERT INTO PELICULAS VALUES(30, 'LA FLOR DE MI SECRETO', 'COQUETEO ENTRE REALIDAD Y FICCI�N, SE LE OLVID� ARMAR UN ARGUMENTO', 1, 'ACC', '22/09/1995');
INSERT INTO PELICULAS VALUES(31, 'SALVAR AL SOLDADO RYAN', 'MISI�N LLEVADA A CABO POR SOLDADOS AMERICANOS TRAS EL DESEMBARCO DE NORMAND�A', 2, 'ACC', '18/09/1998');
INSERT INTO PELICULAS VALUES(32, 'LA LISTA DE SCHINDLER', 'UN HOMBRE DE ENORME ASTUCIA DISE�A UN AMBICIOSO PLAN PARA GANARSE LA SIMPAT�A DE LOS NAZIS', 2, 'ACC', '04/03/1994');
INSERT INTO PELICULAS VALUES(33, 'EL ESPINAZO DEL DIABLO', 'UN ORFANATO DE HU�RFANOS REPUBLICANOS CONVIVEN CON UN FANTASMA', 6, 'TER','20/04/2001');
INSERT INTO PELICULAS VALUES(34, 'LA FORMA DEL AGUA', 'UNA EXTRA�A CIRATURA ACU�TICA EMPIEZA A SER ESTIDUADA Y SURGE EL AMOR CON ELISA', 6, 'ROM', '01/12/2017');
INSERT INTO PELICULAS VALUES(35, 'EL LABERINTO DEL FAUNO', 'DURANTE LA POSGUERRA UNA NI�A HACE LO IMPOSIBLE POR HIR DE LA NUEVA PAREJA DE SU MADRE', 6, 'FIC', '11/10/2006');
INSERT INTO PELICULAS VALUES(36, 'CHARLIE Y LA F�BRICA DE CHOCOLATE', 'CHARLIE Y SU ABUELO SUE�AN CON VISITA LA F�BRICA DE CHOCOLATE', 7, 'ACC', '12/08/2005');
INSERT INTO PELICULAS VALUES(37, 'BATMAN', 'BATMAN EXPLORA LA CORRUPCI�N Y ENTRA EN CONFLICTOS POR SALVARLA', 7, 'FIC', '04/03/2022');
INSERT INTO PELICULAS VALUES(38, 'BITELCH�S', 'PAREJA JOVEN QUE MUERE EN UN ACCIDENTE POCO DESPU�S DE ESTRENAR SU CASA', 7, 'FIC', '22/07/1988');
INSERT INTO PELICULAS VALUES(39, 'ED WOOD', 'NARRA LA VIDA DEL FAMOSO DIRECTOR DE CINE BIZARRO Y DE CULTO ED WOOOD', 7, 'ACC', '02/06/1995');
INSERT INTO PELICULAS VALUES(40, 'LA DOLCE VITA', 'EXHIBICI�N DEL BEAU MONDE DEL ESPECT�CULO, EL ESC�NDALO Y LA RIQUEZA', 9, 'ACC', '01/06/1981');
INSERT INTO PELICULAS VALUES(41, 'TESIS', 'UN DIRECTOR DE TESIS SE COMPREMENTE A BUSCAR MATERIAL EN LA VIDEOTECA DE LA FACULTAD Y ES HALLADO MUERTO', 8, 'TER', '12/04/1996');
INSERT INTO PELICULAS VALUES(42, 'LOS OTROS', 'UNA FERVIENTE CAT�LICA, DECIDE TRASLADARSE A UN MISTERIOSO CASER�N CON SUS DOS HIJOS', 8, 'FIC', '07/09/2001');
INSERT INTO PELICULAS VALUES(43, 'MAR ADENTRO', 'RAM�N POSTRADO EN UNA CAMA DESEA QUE TERMINE SU VIDA', 8, 'ROM', '03/09/2004');
INSERT INTO PELICULAS VALUES(44, 'ABRE LOS OJOS','NURIA MOVIDA POR CELOS PROVOCA UN ACCIDENTE DE COCHE', 8, 'FIC', '19/12/1997');


--Insertamos actores
INSERT INTO ACTORES VALUES(1, 'ANTONIO', 'BANDERAS', 'ESPA�OLA', '10/08/1960');
INSERT INTO ACTORES VALUES(2, 'LEONARNO', 'DICAPRIO', 'ESTADOUNIDENSE', '11/11/1974');
INSERT INTO ACTORES VALUES(3, 'CARMEN', 'MAURA', 'ESPA�OLA', '15/09/1945');
INSERT INTO ACTORES VALUES(4, 'CATE', 'BLANCHETT', 'ESTADOUNIDENSE', '14/05/1969');
INSERT INTO ACTORES VALUES(5, 'BIBIANA', 'FERN�NDEZ', 'ESPA�OLA', '13/02/1954');
INSERT INTO ACTORES VALUES(6, 'WOODY', 'ALLEN', 'ESTADOUNIDENSE', '30/11/1935');
INSERT INTO ACTORES VALUES(7, 'MERYL', 'STREEP', 'ESTADOUNIDENSE', '22/06/1949');
INSERT INTO ACTORES VALUES(8, 'KURT', 'RUSSELL', 'ESTADOUNIDENSE', '17/03/1951');
INSERT INTO ACTORES VALUES(9, 'ZOE', 'BELL', 'NEOZALANDESA', '17/11/1978');
INSERT INTO ACTORES VALUES(10, 'JEFF', 'DANIELS', 'ESTADOUNIDENSE', '19/02/1955');
INSERT INTO ACTORES VALUES(11, 'MIA', 'FARROW', 'ESTADOUNIDENSE', '09/02/1945');
INSERT INTO ACTORES VALUES(12, 'GRIFFIN', 'DUNNE', 'ESTADOUNIDENSE', '08/06/1955');
INSERT INTO ACTORES VALUES(13, 'ROSANNA', 'ARQUETTE', 'ESTADOUNIDENSE', '10/08/1959');
INSERT INTO ACTORES VALUES(14, 'TOPHER', 'GRACE', 'ESTADOUNIDENSE', '10/08/1959');
INSERT INTO ACTORES VALUES(15, 'MARY ELISABETH', 'WINSTEAD', 'ESTADOUNIDENSE', '28/11/1984');
INSERT INTO ACTORES VALUES(16, 'MADELEINE', 'KNIGHT', 'ESTADOUNIDENSE', '15/05/1937');
INSERT INTO ACTORES VALUES(17, 'HENRY', 'THOMAS', 'ESTADOUNIDENSE', '09/09/1971');
INSERT INTO ACTORES VALUES(18, 'DREW', 'BARRYMORE', 'ESTADOUNIDENSE', '22/02/1975');
INSERT INTO ACTORES VALUES(19, 'BILLY', 'CRYSTAL', 'ESTADOUNIDENSE', '14/03/1948');
INSERT INTO ACTORES VALUES(20, 'JULIA', 'LOUIS DREYFUS', 'ESTADOUNIDENSE', '13/01/1961');
INSERT INTO ACTORES VALUES(21, 'ELENA', 'ANAYA', 'ESPA�OLA', '17/07/1975');
INSERT INTO ACTORES VALUES(22, 'BLANCA', 'SU�REZ', 'ESPA�OLA', '21/10/1988');
INSERT INTO ACTORES VALUES(23, 'ROBERT', 'DE NIRO', 'ESTADOUNIDENSE','17/08/1943');
INSERT INTO ACTORES VALUES(24, 'JERRY', 'LEWIS', 'ESTADOUNIDENSE', '16/03/1926');
INSERT INTO ACTORES VALUES(25, 'DIAHNNE', 'ABBOTT', 'ESTADOUNIDENSE', '01/05/1945');
INSERT INTO ACTORES VALUES(34, 'LORRAINE', 'GARRY', 'ESTADOUNIDENSE', '16/08/1937');
INSERT INTO ACTORES VALUES(26, 'JOE', 'PESCI', 'ESTADOUNIDENSE', '09/02/1943');
INSERT INTO ACTORES VALUES(33, 'ROBERT', 'SHAW', 'ESTADOUNIDENSE', '09/08/1927');
INSERT INTO ACTORES VALUES(27, 'BRAD', 'PITT', 'ESTADOUNIDENSE', '18/12/1963');
INSERT INTO ACTORES VALUES(28, 'LEONARDO', 'DICAPRIO', 'ESTADOUNIDENSE', '11/11/1974');
INSERT INTO ACTORES VALUES(29, 'MARGOT', 'ROBBIE', 'ESTADOUNIDENSE', '02/07/1990');
INSERT INTO ACTORES VALUES(30, 'JODIE', 'FOSTER', 'ESTADOUNIDENSE', '19/11/1962');
INSERT INTO ACTORES VALUES(31, 'ROY', 'SCHEIDER', 'ESTADOUNIDENSE', '10/11/1931');
INSERT INTO ACTORES VALUES(32, 'RICHARD', 'DREYFUSS', 'ESTADOUNIDENSE', '29/10/1947');
INSERT INTO ACTORES VALUES(35, 'SAMUEL', 'L JACKSON', 'ESTADOUNIDENSE', '21/12/1948');
INSERT INTO ACTORES VALUES(36, 'JENNIFER', 'JASON', 'ESTADOUNIDENSE', '05/02/1962');
INSERT INTO ACTORES VALUES(37, 'VERA', 'FARMIGA', 'ESTADOUNIDENSE', '06/08/1973');
INSERT INTO ACTORES VALUES(39, 'CARMEN', 'MAURA', 'ESPA�OLA', '15/09/1945');
INSERT INTO ACTORES VALUES(40, 'ROSY', 'DE PALMA', 'ESPA�OLA', '16/09/1964');
--Insertamos las pelis
INSERT INTO ACTORES_PELIS VALUES(40, 20);
INSERT INTO ACTORES_PELIS VALUES(28, 19);
INSERT INTO ACTORES_PELIS VALUES(35, 18);
INSERT INTO ACTORES_PELIS VALUES(32, 17);
INSERT INTO ACTORES_PELIS VALUES(31, 17);
INSERT INTO ACTORES_PELIS VALUES(30, 16);
INSERT INTO ACTORES_PELIS VALUES(23, 16);
INSERT INTO ACTORES_PELIS VALUES(39, 20);
INSERT INTO ACTORES_PELIS VALUES(37, 19);
INSERT INTO ACTORES_PELIS VALUES(36, 18);
INSERT INTO ACTORES_PELIS VALUES(29, 15);
INSERT INTO ACTORES_PELIS VALUES(27, 15);
INSERT INTO ACTORES_PELIS VALUES(26, 14);
INSERT INTO ACTORES_PELIS VALUES(1, 20);
INSERT INTO ACTORES_PELIS VALUES(34, 17);
INSERT INTO ACTORES_PELIS VALUES(28, 15);
INSERT INTO ACTORES_PELIS VALUES(23, 14);
INSERT INTO ACTORES_PELIS VALUES(25, 11);
INSERT INTO ACTORES_PELIS VALUES(33, 17);
INSERT INTO ACTORES_PELIS VALUES(24, 11);
INSERT INTO ACTORES_PELIS VALUES(23, 11);
INSERT INTO ACTORES_PELIS VALUES(22, 13);
INSERT INTO ACTORES_PELIS VALUES(1, 13);
INSERT INTO ACTORES_PELIS VALUES(21, 13);
INSERT INTO ACTORES_PELIS VALUES(19, 10);
INSERT INTO ACTORES_PELIS VALUES(20, 10);
INSERT INTO ACTORES_PELIS VALUES(17, 9);
INSERT INTO ACTORES_PELIS VALUES(18, 9);
INSERT INTO ACTORES_PELIS VALUES(14, 8);
INSERT INTO ACTORES_PELIS VALUES(15, 8);
INSERT INTO ACTORES_PELIS VALUES(16, 8);
INSERT INTO ACTORES_PELIS VALUES(13,7);
INSERT INTO ACTORES_PELIS VALUES(12,7);
INSERT INTO ACTORES_PELIS VALUES(1,1);
INSERT INTO ACTORES_PELIS VALUES(3,1);
INSERT INTO ACTORES_PELIS VALUES(5,1);
INSERT INTO ACTORES_PELIS VALUES(2,3);
INSERT INTO ACTORES_PELIS VALUES(4,3);
INSERT INTO ACTORES_PELIS VALUES(6,4);
INSERT INTO ACTORES_PELIS VALUES(7,4);
INSERT INTO ACTORES_PELIS VALUES(8,5);
INSERT INTO ACTORES_PELIS VALUES(9,5);
INSERT INTO ACTORES_PELIS VALUES(10,6);
INSERT INTO ACTORES_PELIS VALUES(11, 6);

-----------------------------------------------------------------------------------------
-- FUNCIONES
-- concat
-- initcap pone a mayuscula la primera letra de cada palabra
select initcap('hola amigos') from dual;
select initcap(TITULO) from PELICULAS;
select initcap(NOMBRE || ' ' || APELLIDO) as NyAp from DIRECTORES;

-- lpad
select lpad('alumno',12,'clase-') from dual;
select lpad('alumno',10,'clase-') from dual;
select lpad('alumno',24,'clase-') from dual;

select TITULO, lpad(COD_TEMA, 8, 'tema: ') from PELICULAS;
select TITULO, rpad(COD_TEMA, 9, ': tema') from PELICULAS;

-- Realiza una select que complete el codigo de la pelicula de la tabla peliculas hasta 3
-- digitos junto con el titulo de la misma. Si su tamaño es menos añade 0 a la izquierda
-- hasta completarlo
select  lpad(COD_PELICULA,3,'0'), TITULO from PELICULAS;

-- ltrim (existe ltrim, rtrim y trim)
select ltrim('la casa', 'la') from DUAL;

-- replace
select replace('    xxx.oracle.com', 'x', 'w') from DUAL;

-- Cambiar el nombre de todos los actores, apellido y nacionalidad ordenados por apellido sustituyendo
-- totas las ñ por ni en los tres atributos
select NOMBRE,APELLIDO,NACIONALIDAD from ACTORES;
select replace(NOMBRE, upper('Ñ'), upper('NI')) from ACTORES;
select replace(NOMBRE || ' ' || APELLIDO || ' ' || NACIONALIDAD,  upper('Ñ'), upper('NI')) from ACTORES;

-- substr (se cuenta a partir de la posición 0)
select substr('www.oracle.com',1,10) from DUAL;
select substr('www.oracle.com',5,6) from DUAL;

-- length
select length('www.oracle.com') from dual;
select length('5983163'), lpad('5983163',8, '0') from DUAL;

-- select que devuelva el titulo de las peliculas ordenando el resultado de mayor a menor longitud.
select TITULO from PELICULAS
order by length(TITULO);

-- titulos de peliculas que contengan la palabra soldado y nos indique la posicion dentro de la cadena
select TITULO, instr(upper(TITULO), 'SOLDADO') from PELICULAS
where instr(upper(TITULO), 'SOLDADO') > 0;

-- translate
select translate(' JORGE LUIS BORGES', 'OSG', '056') from dual;

-- reverse
select reverse('la casa lila') from DUAL;

select * from VENTA;
select CANTIDAD + nvl(COMISION,0) from VENTA; -- de peluqueria

-- FUNCIONES NUMÉRICAS------------------------------------------------------------------------------------

-- round aka redondeo
select round(8.239,2) from dual;
select round(12.345) from dual;

-- trunc aka truncar
select trunc(12.678) from dual;
select trunc(12.9999,2) from DUAL;
select trunc(12.9999,-1) from DUAL; -- no funciona correctamente

-- mod aka modulo
select mod(45,2) from DUAL;

-- power aka potencia
select power(16,2) from dual; -- 16 elevado a 2

-- sqrt aka raiz cuadrada

-- sign devuelve el signo de un numero
select sign(-20) from dual;
select sign(20) from dual;

-- abs aka valor absoluto

-- Incrementa el valor del precio del cosmetico en 1.345
--      Redondea en 2 decimales y trunca en 2 decimales
update COSMETICO
set PRECIO = (PRECIO + 1.345);

select round(PRECIO,2) from COSMETICO;
select trunc(PRECIO,2) from COSMETICO;

-- FUNCIONES DE FECHA -------------------------------------------------------------------------------------------

alter session set nls_date_format = 'DD-MM-YYYY'; -- para cambiar la estructura de la fecha

-- interval
select interval '130' minute from dual;
select sysdate + interval '24' hour from DUAL;
select sysdate + interval  '2' year from DUAL;

-- add_months
select add_months(sysdate, 5) from dual;
select add_months('12-02-22',7) from DUAL;

-- months_between, meses entre dos fechas
select months_between(sysdate, '02/03/2001') from dual;

-- next_day
select next_day(sysdate, 'lunes') from dual;

-- last_day

-- añade 12 meses al dia de hoy
select add_months(sysdate,12) from dual;

-- extract
select extract(MONTH from sysdate) from dual;

-- CONSULTAS CORRELACCIONADAS ---------------------------------------------------------------------------------

