-- * ACT5

-- ! Script aula virtual
    DROP TABLE TRATAMIENTO;
    DROP TABLE CLIENTE_TRATAMIENTO;
    DROP TABLE CITA;
    DROP TABLE VENTA;
    DROP TABLE COSMETICO;
    DROP TABLE SERVICIO;
    DROP TABLE EMPLEADO;
    DROP TABLE CLIENTE;
    --CLIENTES DE MI NEGOCIO DE ESTÉTICA
    CREATE TABLE CLIENTE(
        DNI VARCHAR2(12) PRIMARY KEY,
        NOMBRE VARCHAR2(30),
        PROFESION VARCHAR2(30),
        TFNO NUMBER(11),
        DIRECCION VARCHAR2(60)
    );
    INSERT INTO CLIENTE VALUES('05912345N', 'ANTONIO', 'CONDUCTOR', 67565723, 'C/SOLEDAD 27 PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05942445S', 'Ana', 'ENFERMERA', 65565723, 'C/OLIVO 2 3ºA PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05913425T', 'ANA', 'ENFERMERA', 68888723, 'C/APRISCO 44 2ºB PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('70913425W', 'FEDERICO', 'PROFESOR', 65555723, 'C/OLIVO 12 5ºA PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('03333333S', 'PEPE', 'ENFERMERA', 68888723, 'C/APRISCO 78 2ºB PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05753254T', 'ana', 'PROFESORA', 67322723, 'C/GOYA 56 5ºB PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('02333235J', 'LUISA', 'ENFERMERA', 68888756, 'C/GOYA 56 2ºB PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05334259T', 'PEDRO', 'ENFERMERO', 66544723, 'C/APRISCO 56 6ºB ARGAMASILLA CVA');
    INSERT INTO CLIENTE VALUES('05900025K', 'JOSEFA', 'CONDUCTORA', 69999977, 'C/OURENSE 3 6ºC PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05313525D', 'ANA', 'CONDUCTORA', 68845723, 'C/LARGA 45 1ºB ARGAMASILLA CVA');
    --TABLA EMPLEADO DE MI NEGOCIO DE EST�TICA
    CREATE TABLE EMPLEADO(
        DNI VARCHAR2(12) PRIMARY KEY,
        NOMBRE VARCHAR2(30),
        ESPECIALIDAD VARCHAR2(30)
    );
    INSERT INTO EMPLEADO VALUES('70898989S', 'ÁNGELA', 'PELUQUERÍA');
    INSERT INTO EMPLEADO VALUES('70868686L', 'Sandra', 'PELUQUERÍA');
    INSERT INTO EMPLEADO VALUES('72312222R', 'ANA', 'ESTÉTICA');
    INSERT INTO EMPLEADO VALUES('05965433M', 'ANTONIO', 'PELUQUERÍA');
    INSERT INTO EMPLEADO VALUES('05933333S', 'SOFÍA', 'ESTÉTICA');
    --SERVICIOS QUE SE PRESTAN EN EL SAL�N DE BELLEZA
    CREATE TABLE SERVICIO(
        COD VARCHAR2(10) PRIMARY KEY,
        DESCRIPCION VARCHAR2(200),
        PRECIO NUMBER(5,2));
    INSERT INTO SERVICIO VALUES('COR-PC', 'Corte de pelo corto', 10);
    INSERT INTO SERVICIO VALUES('COR-PL', 'Corte de pelo largo', 12);
    INSERT INTO SERVICIO VALUES('TIN-PC', 'Tinte de pelo corto', 8);
    INSERT INTO SERVICIO VALUES('TIN-PL', 'Tinte de pelo largo', 11);
    INSERT INTO SERVICIO VALUES('CER-MP', 'Cera de medias piernas', 7);
    INSERT INTO SERVICIO VALUES('CER-EP', 'Cera de enteras piernas', 10);
    INSERT INTO SERVICIO VALUES('CER-AX', 'Cera axilas', 5);
    INSERT INTO SERVICIO VALUES('M_ESP', 'Masaje espalda', 20);
    INSERT INTO SERVICIO VALUES('M_PIE', 'Masaje piernas', 25);
    INSERT INTO SERVICIO VALUES('M_FAC', 'Masaje facial', 20);

    --Tabla de cosm�tico
    CREATE TABLE COSMETICO(
        COD VARCHAR2(10) PRIMARY KEY,
        NOMBRE VARCHAR2(30),
        PRECIO NUMBER(5,2)
    );
    INSERT INTO COSMETICO VALUES('C001', 'Cream de día SENSILIS', 23);
    INSERT INTO COSMETICO VALUES('C002', 'Cream de noche NIVEA', 45);
    INSERT INTO COSMETICO VALUES('CH01', 'Champú anticaída', 17);
    INSERT INTO COSMETICO VALUES('CH02', 'Champú anticaspa', 19);
    INSERT INTO COSMETICO VALUES('TI01', 'Tinte rubio', 10);
    INSERT INTO COSMETICO VALUES('TI02', 'Tinte castaño', 10);
    INSERT INTO COSMETICO VALUES('TI03', 'Tinte moreno', 10);
    INSERT INTO COSMETICO VALUES('PE01', 'Fijador Permanente', 45);
    INSERT INTO COSMETICO VALUES('CP01', 'Laca pelo corto', 10);
    INSERT INTO COSMETICO VALUES('CP02', 'Corte media pelena', 12);
    INSERT INTO COSMETICO VALUES('CP03', 'Corte pelo largo', 15);

    --Tabla de venta
    CREATE TABLE VENTA(
        COD_VENTA NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        COD_COSMET VARCHAR2(10),
        DNI_EMPLEADO VARCHAR2(12),
        DNI_CLIENTE VARCHAR2(12),
        FECHA_VENTA DATE,
        COMISION NUMBER(5,2),
        CANTIDAD NUMBER(5),
        FOREIGN KEY (COD_COSMET) REFERENCES COSMETICO(COD),
        FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI),
        FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI)
    );

    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CP03','70898989S', '05912345N',TO_DATE('22/02/2020 12:00','DD/MM/YYYY HH:MI'), NULL, 1); 
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH01','70898989S', '05912345N',TO_DATE('22/02/2020 12:00','DD/MM/YYYY HH:MI'), 1, 3);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH02','70868686L', '05912345N',TO_DATE('22/03/2020 12:00','DD/MM/YYYY HH:MI'), 1.5, 2);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('TI01','70868686L', '05942445S',TO_DATE('14/02/2020 12:00','DD/MM/YYYY HH:MI'), NULL, 1);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH01','70868686L', '05942445S',TO_DATE('14/03/2020 11:10', 'DD/MM/YYYY HH:MI'), 0.5, 2);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CP01','05965433M', '05913425T',TO_DATE('4/02/2020 10:25','DD/MM/YYYY HH:MI'), NULL, 1);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CP01','05965433M', '02333235J',TO_DATE('15/04/2020 11:25','DD/MM/YYYY HH:MI'), NULL, 1);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH01','72312222R', '05900025K',TO_DATE('15/04/2020 10:25','DD/MM/YYYY HH:MI'), 3, 5);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('C001','72312222R', '05900025K',TO_DATE('15/04/2020 09:25','DD/MM/YYYY HH:MI'), 1, 2);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH01','05933333S', '05313525D',TO_DATE('3/05/2020 12:25', 'DD/MM/YYYY HH:MI'), 1, 1);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('C002','05933333S', '05313525D',TO_DATE('3/05/2020 12:25','DD/MM/YYYY HH:MI'), 0.5, 1);

    --Tabla de las citas
    CREATE TABLE CITA(
        NUM_CITA NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        COD_SERVICIO VARCHAR2(10),
        DNI_EMPLEADO VARCHAR2(12),
        DNI_CLIENTE VARCHAR2(12),
        FECHA_HORA DATE,
        FOREIGN KEY (COD_SERVICIO) REFERENCES SERVICIO(COD),
        FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI),
        FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI)
    );

    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('COR-PC', '70898989S', '05313525D', TO_DATE('03/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('COR-PL', '70898989S', '05313525D', TO_DATE('04/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('COR-PL', '70898989S', '05900025K', TO_DATE('06/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('M_ESP', '05933333S', '05900025K', TO_DATE('07/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('M_ESP', '05933333S', '05900025K', TO_DATE('07/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('M_ESP', '05933333S', '05900025K', TO_DATE('07/07/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('M_ESP', '05933333S', '05900025K', TO_DATE('07/08/2023 12:25','DD/MM/YYYY HH:MI'));

    --Tabla de tratamiento que toma el cliente
    CREATE TABLE TRATAMIENTO(
        COD VARCHAR2(10) PRIMARY KEY,
        DESCRIPCION VARCHAR2(100)
    );

    INSERT INTO TRATAMIENTO VALUES('AL1','ALERGIA AL LÁTEX');
    INSERT INTO TRATAMIENTO VALUES('AL2','ALERGIA AL TINTE');
    INSERT INTO TRATAMIENTO VALUES('DM','DERMATITIS ATÓPICA');
    INSERT INTO TRATAMIENTO VALUES('AL3','ALERGIA AL CHAMPÚ CON QUÍMICO');

    --Tabla de tratamiento que toma alguno de nuestros clientes
    CREATE TABLE CLIENTE_TRATAMIENTO(
        DNI_CLIENTE VARCHAR2(12),
        COD_TRATAMIENTO VARCHAR2(10),
        PRIMARY KEY (DNI_CLIENTE, COD_TRATAMIENTO),
        FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI),
        FOREIGN KEY (COD_TRATAMIENTO) REFERENCES TRATAMIENTO(COD) 
    );

    INSERT INTO CLIENTE_TRATAMIENTO VALUES('05912345N', 'AL3');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('05913425T', 'AL2');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('05913425T', 'DM');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('70913425W', 'AL3');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('70913425W', 'AL1');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('02333235J', 'AL2');
-- ! Fin del script

-------------------------------------------------------------------------------------------
--? 1. Consulta todos los datos de los EMPLEADOS de la peluquería.
SELECT * FROM EMPLEADO;

--? 2. Consulta el NOMBRE y la ESPECIALIDAD de los EMPLEADOS de la peluquería.
SELECT NOMBRE, ESPECIALIDAD FROM EMPLEADO;

--? 3. Consulta la DESCRIPCIÓN de los servicios que se ofrecen en la peluquería junto a sus precios.
SELECT DESCRIPCION, PRECIO FROM SERVICIO;

--? 4. Cuenta el número de distintos servicios que ofrece nuestra peluquería.
SELECT COUNT(*) FROM SERVICIO;

--? 5. Cuenta el número total de empleados que tiene nuestra peluquería.
SELECT COUNT(*) FROM EMPLEADO;

--? 6. Saca un listado de todos los datos de los cosméticos que se venden en nuestra peluquería.
SELECT * FROM COSMETICO;

--? 7. Saca un listado del NOMBRE del cosmético junto con su PRECIO.
SELECT NOMBRE, PRECIO FROM COSMETICO;

--? 8. Saca un listado del COSMÉTICO/OS más barato.
SELECT * 
FROM COSMETICO 
    WHERE PRECIO = (SELECT MIN(PRECIO) FROM COSMETICO);

--? 9. Saca un listado del COSMÉTICO/OS más caro.
SELECT * 
FROM COSMETICO 
    WHERE PRECIO = (SELECT MAX(PRECIO) FROM COSMETICO);

--? 10. Saca un listado de los nombres y teléfonos de todas aquellas clientas
--?  que sean ‘ENFERMERA’ O ‘enfermera’. (Cuidado con las mayúsculas o minúsculas).
SELECT NOMBRE, TFNO 
FROM CLIENTE
    WHERE UPPER(PROFESION) LIKE 'ENFERMERA';

--? 11. Saca un listado de los nombres y teléfonos de todos aquellos clientes que 
--? sean ‘ENFERMERO’, ‘ENFERMERA’, ‘enfermero’, ‘enfermera’. (Trabaja con el comodín y con UPPER o LOWER).
SELECT NOMBRE, TFNO
FROM CLIENTE
    WHERE UPPER(PROFESION) IN ('ENFERMERO','ENFERMERA');

--? 12. Saca un listado de los NOMBRES y PRECIO de los cosméticos cuyo precio sea inferior a 20.
SELECT NOMBRE, PRECIO
FROM COSMETICO
    WHERE PRECIO < 20;

--? 13. Saca un listado de los distintos tipos de TINTE que ofrecemos en la peluquería 
--? junto a su precio, ordena por NOMBRE. (Usa comodín correctamente, la palabra TINTE 
--? no sabemos en que posición se encuentra dentro del nombre).
SELECT NOMBRE, PRECIO
FROM COSMETICO