-- * ACT6

-- ! Script aula virtual
    DROP TABLE TRATAMIENTO;
    DROP TABLE CLIENTE_TRATAMIENTO;
    DROP TABLE CITA;
    DROP TABLE VENTA;
    DROP TABLE COSMETICO;
    DROP TABLE SERVICIO;
    DROP TABLE EMPLEADO;
    DROP TABLE CLIENTE;

    --CLIENTES DE MI NEGOCIO DE ESTÉTICA
    CREATE TABLE CLIENTE(
        DNI VARCHAR2(12) PRIMARY KEY,
        NOMBRE VARCHAR2(30),
        PROFESION VARCHAR2(30),
        TFNO NUMBER(11),
        DIRECCION VARCHAR2(60)
    );
    INSERT INTO CLIENTE VALUES('05912345N', 'ANTONIO', 'CONDUCTOR', 67565723, 'C/SOLEDAD 27 PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05942445S', 'Ana', 'ENFERMERA', 65565723, 'C/OLIVO 2 3ºA PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05913425T', 'ANA', 'ENFERMERA', 68888723, 'C/APRISCO 44 2ºB PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('70913425W', 'FEDERICO', 'PROFESOR', 65555723, 'C/OLIVO 12 5ºA PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('03333333S', 'PEPE', 'ENFERMERA', 68888723, 'C/APRISCO 78 2ºB PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05753254T', 'ana', 'PROFESORA', 67322723, 'C/GOYA 56 5ºB PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('02333235J', 'LUISA', 'ENFERMERA', 68888756, 'C/GOYA 56 2ºB PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05334259T', 'PEDRO', 'ENFERMERO', 66544723, 'C/APRISCO 56 6ºB ARGAMASILLA CVA');
    INSERT INTO CLIENTE VALUES('05900025K', 'JOSEFA', 'CONDUCTORA', 69999977, 'C/OURENSE 3 6ºC PUERTOLLANO');
    INSERT INTO CLIENTE VALUES('05313525D', 'ANA', 'CONDUCTORA', 68845723, 'C/LARGA 45 1ºB ARGAMASILLA CVA');
    --TABLA EMPLEADO DE MI NEGOCIO DE EST�TICA
    CREATE TABLE EMPLEADO(
        DNI VARCHAR2(12) PRIMARY KEY,
        NOMBRE VARCHAR2(30),
        ESPECIALIDAD VARCHAR2(30)
    );
    INSERT INTO EMPLEADO VALUES('70898989S', '�?NGELA', 'PELUQUER�?A');
    INSERT INTO EMPLEADO VALUES('70868686L', 'Sandra', 'PELUQUER�?A');
    INSERT INTO EMPLEADO VALUES('72312222R', 'ANA', 'ESTÉTICA');
    INSERT INTO EMPLEADO VALUES('05965433M', 'ANTONIO', 'PELUQUER�?A');
    INSERT INTO EMPLEADO VALUES('05933333S', 'SOF�?A', 'ESTÉTICA');
    --SERVICIOS QUE SE PRESTAN EN EL SAL�N DE BELLEZA
    CREATE TABLE SERVICIO(
        COD VARCHAR2(10) PRIMARY KEY,
        DESCRIPCION VARCHAR2(200),
        PRECIO NUMBER(5,2));
    INSERT INTO SERVICIO VALUES('COR-PC', 'Corte de pelo corto', 10);
    INSERT INTO SERVICIO VALUES('COR-PL', 'Corte de pelo largo', 12);
    INSERT INTO SERVICIO VALUES('TIN-PC', 'Tinte de pelo corto', 8);
    INSERT INTO SERVICIO VALUES('TIN-PL', 'Tinte de pelo largo', 11);
    INSERT INTO SERVICIO VALUES('CER-MP', 'Cera de medias piernas', 7);
    INSERT INTO SERVICIO VALUES('CER-EP', 'Cera de enteras piernas', 10);
    INSERT INTO SERVICIO VALUES('CER-AX', 'Cera axilas', 5);
    INSERT INTO SERVICIO VALUES('M_ESP', 'Masaje espalda', 20);
    INSERT INTO SERVICIO VALUES('M_PIE', 'Masaje piernas', 25);
    INSERT INTO SERVICIO VALUES('M_FAC', 'Masaje facial', 20);

    --Tabla de cosmético
    CREATE TABLE COSMETICO(
        COD VARCHAR2(10) PRIMARY KEY,
        NOMBRE VARCHAR2(30),
        PRECIO NUMBER(5,2)
    );
    INSERT INTO COSMETICO VALUES('C001', 'Cream de día SENSILIS', 23);
    INSERT INTO COSMETICO VALUES('C002', 'Cream de noche NIVEA', 45);
    INSERT INTO COSMETICO VALUES('CH01', 'Champú anticaída', 17);
    INSERT INTO COSMETICO VALUES('CH02', 'Champú anticaspa', 19);
    INSERT INTO COSMETICO VALUES('TI01', 'Tinte rubio', 10);
    INSERT INTO COSMETICO VALUES('TI02', 'Tinte castaño', 10);
    INSERT INTO COSMETICO VALUES('TI03', 'Tinte moreno', 10);
    INSERT INTO COSMETICO VALUES('PE01', 'Fijador Permanente', 45);
    INSERT INTO COSMETICO VALUES('CP01', 'Laca pelo corto', 10);
    INSERT INTO COSMETICO VALUES('CP02', 'Corte media pelena', 12);
    INSERT INTO COSMETICO VALUES('CP03', 'Corte pelo largo', 15);

    --Tabla de venta
    CREATE TABLE VENTA(
        COD_VENTA NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        COD_COSMET VARCHAR2(10),
        DNI_EMPLEADO VARCHAR2(12),
        DNI_CLIENTE VARCHAR2(12),
        FECHA_VENTA DATE,
        COMISION NUMBER(5,2),
        CANTIDAD NUMBER(5),
        FOREIGN KEY (COD_COSMET) REFERENCES COSMETICO(COD),
        FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI),
        FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI)
    );

    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CP03','70898989S', '05912345N',TO_DATE('22/02/2020 12:00','DD/MM/YYYY HH:MI'), NULL, 1); 
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH01','70898989S', '05912345N',TO_DATE('22/02/2020 12:00','DD/MM/YYYY HH:MI'), 1, 3);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH02','70868686L', '05912345N',TO_DATE('22/03/2020 12:00','DD/MM/YYYY HH:MI'), 1.5, 2);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('TI01','70868686L', '05942445S',TO_DATE('14/02/2020 12:00','DD/MM/YYYY HH:MI'), NULL, 1);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH01','70868686L', '05942445S',TO_DATE('14/03/2020 11:10', 'DD/MM/YYYY HH:MI'), 0.5, 2);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CP01','05965433M', '05913425T',TO_DATE('4/02/2020 10:25','DD/MM/YYYY HH:MI'), NULL, 1);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CP01','05965433M', '02333235J',TO_DATE('15/04/2020 11:25','DD/MM/YYYY HH:MI'), NULL, 1);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH01','72312222R', '05900025K',TO_DATE('15/04/2020 10:25','DD/MM/YYYY HH:MI'), 3, 5);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('C001','72312222R', '05900025K',TO_DATE('15/04/2020 09:25','DD/MM/YYYY HH:MI'), 1, 2);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('CH01','05933333S', '05313525D',TO_DATE('3/05/2020 12:25', 'DD/MM/YYYY HH:MI'), 1, 1);
    INSERT INTO VENTA (COD_COSMET, DNI_EMPLEADO, DNI_CLIENTE, FECHA_VENTA, COMISION, CANTIDAD)
    VALUES('C002','05933333S', '05313525D',TO_DATE('3/05/2020 12:25','DD/MM/YYYY HH:MI'), 0.5, 1);

    --Tabla de las citas
    CREATE TABLE CITA(
        NUM_CITA NUMBER(8) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        COD_SERVICIO VARCHAR2(10),
        DNI_EMPLEADO VARCHAR2(12),
        DNI_CLIENTE VARCHAR2(12),
        FECHA_HORA DATE,
        FOREIGN KEY (COD_SERVICIO) REFERENCES SERVICIO(COD),
        FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI),
        FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI)
    );

    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('COR-PC', '70898989S', '05313525D', TO_DATE('03/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('COR-PL', '70898989S', '05313525D', TO_DATE('04/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('COR-PL', '70898989S', '05900025K', TO_DATE('06/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('M_ESP', '05933333S', '05900025K', TO_DATE('07/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('M_ESP', '05933333S', '05900025K', TO_DATE('07/06/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('M_ESP', '05933333S', '05900025K', TO_DATE('07/07/2023 12:25','DD/MM/YYYY HH:MI'));
    INSERT INTO CITA (COD_SERVICIO, DNI_EMPLEADO, DNI_CLIENTE, FECHA_HORA)
        VALUES ('M_ESP', '05933333S', '05900025K', TO_DATE('07/08/2023 12:25','DD/MM/YYYY HH:MI'));

    --Tabla de tratamiento que toma el cliente
    CREATE TABLE TRATAMIENTO(
        COD VARCHAR2(10) PRIMARY KEY,
        DESCRIPCION VARCHAR2(100)
    );

    INSERT INTO TRATAMIENTO VALUES('AL1','ALERGIA AL L�?TEX');
    INSERT INTO TRATAMIENTO VALUES('AL2','ALERGIA AL TINTE');
    INSERT INTO TRATAMIENTO VALUES('DM','DERMATITIS ATÓPICA');
    INSERT INTO TRATAMIENTO VALUES('AL3','ALERGIA AL CHAMPÚ CON QU�?MICO');

    --Tabla de tratamiento que toma alguno de nuestros clientes
    CREATE TABLE CLIENTE_TRATAMIENTO(
        DNI_CLIENTE VARCHAR2(12),
        COD_TRATAMIENTO VARCHAR2(10),
        PRIMARY KEY (DNI_CLIENTE, COD_TRATAMIENTO),
        FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTE(DNI),
        FOREIGN KEY (COD_TRATAMIENTO) REFERENCES TRATAMIENTO(COD) 
    );

    INSERT INTO CLIENTE_TRATAMIENTO VALUES('05912345N', 'AL3');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('05913425T', 'AL2');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('05913425T', 'DM');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('70913425W', 'AL3');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('70913425W', 'AL1');
    INSERT INTO CLIENTE_TRATAMIENTO VALUES('02333235J', 'AL2');
-- ! Fin del script

-------------------------------------------------------------------------------------------
--? 1. Saca un listado de los NOMBRES de los clientes que han comprado cosméticos, ordena alfabéticamente.
SELECT CLIENTE.NOMBRE 
FROM CLIENTE JOIN VENTA
ON CLIENTE.DNI = VENTA.DNI_CLIENTE
    WHERE UPPER(venta.cod_cosmet) LIKE 'C%' 
    ORDER BY CLIENTE.NOMBRE ASC;

--? 2. Saca un listado de los NOMBRES de los cosméticos que se han vendido, ordena alfabéticamente.
SELECT COSMETICO.NOMBRE
FROM COSMETICO JOIN VENTA
ON COSMETICO.COD = VENTA.COD_COSMET
    ORDER BY COSMETICO.NOMBRE ASC;

--? 3. Saca un listado de los NOMBRES de los cosméticos que se han vendido junto al total de ellos. 
--?    (Ten en cuenta que en una misma venta se puede vender más de un producto(existe el campo CANTIDAD)).
SELECT COSMETICO.NOMBRE, SUM(VENTA.CANTIDAD) AS TOTAL
FROM COSMETICO JOIN VENTA
ON COSMETICO.COD = VENTA.COD_COSMET
    WHERE VENTA.COD_COSMET LIKE 'C%' --! Maybe se puede con --> WHERE VENTA.COD_COSMET IS NOT NULL
    GROUP BY COSMETICO.NOMBRE
    ORDER BY TOTAL DESC;
    
--? 4. Escribe un listado de los NOMBRES de los clientes que toman tratamiento y la DESCRIPCIÓN del mismo.
SELECT CLIENTE.NOMBRE, CLIENTE_TRATAMIENTO.COD_TRATAMIENTO, TRATAMIENTO.DESCRIPCION
FROM CLIENTE JOIN CLIENTE_TRATAMIENTO
ON CLIENTE.DNI = CLIENTE_TRATAMIENTO.DNI_CLIENTE
JOIN TRATAMIENTO
ON CLIENTE_TRATAMIENTO.COD_TRATAMIENTO = TRATAMIENTO.COD;
    
--? 5. Haz un listado ordenado del NOMBRE del cosmético/os cuyo precio sea el más bajo.
SELECT NOMBRE
FROM COSMETICO
    WHERE PRECIO = (SELECT MIN(PRECIO) FROM COSMETICO)
    ORDER BY NOMBRE ASC;
    
--? 6. Haz un listado del NOMBRE/ES del cosmético/os cuyo precio sea igual que el del precio de ‘TINTE RUBIO’.
SELECT NOMBRE
FROM COSMETICO
    WHERE PRECIO = (SELECT PRECIO FROM COSMETICO
        WHERE UPPER(NOMBRE) LIKE 'TINTE RUBIO')
    ORDER BY NOMBRE ASC;

--? 7. Haz un listado de los NOMBRES de los CLIENTES junto con el NOMBRE del empleado que le ha atendido.
SELECT CLIENTE.NOMBRE AS CLIENTE, EMPLEADO.NOMBRE AS EMPLEADO
FROM CLIENTE JOIN CITA
ON CLIENTE.DNI = CITA.DNI_CLIENTE
JOIN EMPLEADO
ON CITA.DNI_EMPLEADO = EMPLEADO.DNI;
    
--? 8. Haz un listado de los NOMBRES de los CLIENTES junto con el SERVICIO que se ha hecho o que se hará.
SELECT CLIENTE.NOMBRE,TRATAMIENTO.DESCRIPCION
FROM CLIENTE JOIN CLIENTE_TRATAMIENTO
ON CLIENTE.DNI = CLIENTE_TRATAMIENTO.DNI_CLIENTE
JOIN TRATAMIENTO
ON CLIENTE_TRATAMIENTO.COD_TRATAMIENTO = TRATAMIENTO.COD;

--? 9. Haz un listado de los NOMBRES de los cosméticos que se ha comprado un cliente y el nombre del 
--?    empleado que se lo vendió. Listado con NOMBRE del empleado, NOMBRE del cliente y NOMBRE del cosmético.
SELECT EMPLEADO.NOMBRE, CLIENTE.NOMBRE, COSMETICO.NOMBRE
FROM EMPLEADO JOIN VENTA
ON EMPLEADO.DNI = VENTA.DNI_EMPLEADO
JOIN CLIENTE
ON CLIENTE.DNI = VENTA.DNI_EMPLEADO
JOIN COSMETICO 
ON COSMETICO.COD = VENTA.COD_COSMET;
    
--? 10. Haz un listado de todos los datos de aquellos clientes que no sean ni PROFESOR, ni CONDUCTOR. 
--?     (Da igual el sexo de la persona).
    
--? 11. Saca un listado de los nombres de los SERVICIOS que tenemos citados ordenado por fecha.
    
--? 12. Saca un listado de todos los SERVICIOS de la peluquería cuyo precio esté entre 5 y 15 euros.
    
--? 13. Saca un listado de los NOMBRES que se han hecho algún SERVICIO cuyo precio esté 
--?     comprendido entre 10 y 15 euros.

--? 14. Saca un listado de los NOMBRES de los cosméticos cuyo precio sea menor de 15 euros.

--? 15. Saca un listado de los NOMBRES de los clientes que han comprado algún 
--?     cosmético por valor menor de 15 euros.

--? 16. Saca un listado del número de CLIENTES que tenemos de cada PROFESIÓN.
    
--? 17. Saca un listado del número de EMPLEADOS que tenemos de cada ESPECIALIDAD.